### PR TITLE
Restructure benchmarks module

### PR DESCRIPTION
**Pull request by ilitteri**
Solves #91. This PR should be merged after #92.

## Run all the benchmarks
```
make benchmarks
```

## Run specific benchmarks
```
make benchmark BENCHMARK=benchmark_name
```

## Adding a benchmark
To add a benchmark you just need to:
1. Go to `some_crate/Cargo.toml`
2. Declare your new bench:
  ```toml
  [[bench]]
  name = "<my_new_bench>"
  harness = false
  ```
3. Create `benches/<my_new_bench>_benchmarks.rs`
4. Copy the structure of another bench.
5. Define your benchmark functions in `benches/benchmarks/my_new_bench.rs`

### CODE REVIEW

**Review by MauroToscano — APPROVED** [review]

**Comment by AminArria** [comment]
Question for this, in #110 I followed the steps to add a new benchmark, but I'm getting complaints about `dead-code` any ideas if there is something wrong with the structure or I'm missing something?

**Comment by ilitteri** [comment]
> Question for this, in #110 I followed the steps to add a new benchmark, but I'm getting complaints about `dead-code` any ideas if there is something wrong with the structure or I'm missing something?

I think that I've already encountered with this and if I recall correctly it is due to a bug, but I'll take a look into it.

**Comment by ilitteri** [comment]
> > Question for this, in #110 I followed the steps to add a new benchmark, but I'm getting complaints about `dead-code` any ideas if there is something wrong with the structure or I'm missing something?
> 
> I think that I've already encountered with this and if I recall correctly it is due to a bug, but I'll take a look into it.
> 
> EDIT: Worst case scenario, we allow the lint int `benches/benchmarks/mod.rs`.

Yep, it's a bug. Check the second bullet of [this changelog](https://github.com/bheisler/criterion.rs/blob/master/CHANGELOG.md#changed-10). Let's allow the warning in the module.

**Comment by ilitteri** [comment]
> > > Question for this, in #110 I followed the steps to add a new benchmark, but I'm getting complaints about `dead-code` any ideas if there is something wrong with the structure or I'm missing something?
> > 
> > 
> > I think that I've already encountered with this and if I recall correctly it is due to a bug, but I'll take a look into it.
> > EDIT: Worst case scenario, we allow the lint int `benches/benchmarks/mod.rs`.
> 
> Yep, it's a bug. Check the second bullet of [this changelog](https://github.com/bheisler/criterion.rs/blob/master/CHANGELOG.md#changed-10). Let's allow the warning in the module.

Lint allowed!

**Review by entropidelic — APPROVED** [review]

**Pull request merged**
