### PR TITLE
added EmptyString error variant for FieldElement and UnsignedInteger

### PR DESCRIPTION
**Pull request by startup-dreamer**
## Description

added `EmptyString` error variant for `FieldElement` and `UnsignedInteger`.

Fixes: #487 

## Type of change
- [x] Bug fix
- [x] Optimization

## Checklist
- [x] Linked to Github Issue
- [x] Unit tests added
- [x] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] This change is an Optimization
  - [ ] Benchmarks added/run

### CODE REVIEW

**Comment by MauroToscano** [comment]
It's also a `Bugfix`

**Review by Oppen — APPROVED** [review]

**Comment by startup-dreamer** [comment]
@MauroToscano @Oppen added the required tests you guys should be able to merge now.

**Review by diegokingston — APPROVED** [review]

**Review by MauroToscano — APPROVED** [review]

**Comment by startup-dreamer** [comment]
@schouhy @ajgara @Oppen  Not gonna merge is there any problem same question for #510

**Comment by Oppen** [comment]
There are some conflicts in `math/src/errors.rs` but I guess otherwise it should be merged, it has three approves after all.

**Comment by startup-dreamer** [comment]
@Oppen resolved the conflicts you may merge this now.

**Pull request merged**
