### PR TITLE
feat: Banderwagon implementation

### PR DESCRIPTION
**Pull request by rupam-04**
Tried implementing the serealisation and deserealisation properties of Banderwagon which set it apart from Bandersnatch. However I am not really sure about the tests and ready to accept any advice about them.

### CODE REVIEW

**Comment by MauroToscano** [comment]
Serialization doesn't need to be defined for the curve. You serialize the points of the curve, not the curve, and it's defined elsewhere. Also, add some tests with specifics points obtained from the scripts we use with sage and test the operations with that.

**Comment by rupam-04** [comment]
> Serialization doesn't need to be defined for the curve. You serialize the points of the curve, not the curve, and it's defined elsewhere. Also, add some tests with specifics points obtained from the scripts we use with sage and test the operations with that.

Okay noted working on it

**Comment by rupam-04** [comment]
Added the sage script as comments in the tests

**Comment by rupam-04** [comment]
> Serialization doesn't need to be defined for the curve. You serialize the points of the curve, not the curve, and it's defined elsewhere. Also, add some tests with specifics points obtained from the scripts we use with sage and test the operations with that.

Added the sage script as comments in the tests

**Comment by rupam-04** [comment]
@MauroToscano @diegokingston can this be reviewed and merged if okay?

**Comment by diegokingston** [comment]
This PR is stale, I am going to close it

**Pull request closed without merging**
